apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: API-demo
  title: API-demo
  description: API-demo
spec:
  tag:
    self-service
    eks
  owner: service.owner
  type: resource
parameters:
  - title: Account
    properties:

steps:
  - id: trigger
    name: Create-eks-cluster
    action: trigger:harness-custom-pipeline
    input:
      url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/createekspipeline/pipeline-studio/?branch=dev&connectorRef=account.LephanHH&storeType=REMOTE&repoName=demo-catalog
      inputset:
        aws_account: ${{ parameters.aws_account }}
        aws_region: ${{ parameters.aws_region }}
        aws_vpc: ${{ parameters.aws_vpc }}
      apikey: ${{ parameters.token }}
      showOutputVariables: true
output:
  links:
    - title: Pipeline Details
      url: ${{ steps.trigger.output.PipelineUrl }}
      
