apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: api-demo
  title: api-demo
  description: api-demo
spec:
  owner: DCP
  type: service
  parameters:
    - title: Fill in the repo details
      required:
      - aws_account
      properties:
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken
        aws_account:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: AWS Account
            description: AWS Account selected
            placeholder: Choose an AWS Account
            path: proxy/demo-api
            params:
              action: "listAccounts"          
            valueSelector: Id
            allowArbitraryValues: false             
        aws_account:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: AWS Account
            description: AWS Account selected
            placeholder: Choose an AWS Account
            path: proxy/demo-api
            params:
              action: "listAccounts"          
            valueSelector: Id
            allowArbitraryValues: false    
        aws_region:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: Regions
            description: Regions
            placeholder: Choose a Region
            path: proxy/demo-api
            params:
              action: "listRegions"          
            valueSelector: region
            allowArbitraryValues: false
        vpc:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: VPC
            description: VPC
            placeholder: Select VPC
            path: proxy/demo-api
            params:
              action: "listVPCs"    
              account_id: "abc"
              region: "us-west-2"
            valueSelector: VpcId
            allowArbitraryValues: false          
    - title: reference
      required:
        - aws_account
      properties:
        aws_account:
          type: string
          value: {{ parameters.aws_account}}


  steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        #url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/all/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding/pipeline-studio?storeType=INLINE
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding_Clone_Clone/pipeline-studio?storeType=INLINE
        inputset:
          github_org: ${{ parameters.github_org_name }}
          github_repo: ${{ parameters.github_repo_name }}
          github_username: ${{parameters.github_username}}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          return: ${{steps.trigger.output.RETURN_VAL}},github_org_name: ${{ parameters.github_org_name}},github_repo_name: ${{ parameters.github_repo_name}}



          
