apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: lp-demo
  title: lp-demo
  description: api-demo
spec:
  owner: DCP
  type: service
  parameters:
    - title: Fill in the repo details
      properties:
        test:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: Select-env
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities
            params:
              filter: kind=resource,spec.type=eks,spec.owner=group:default/dcp,metadata.name=aws-31971-dcp-eks-testg-us-west-2-non-prod
            valueSelector: metadata.jenkinsurl
            allowArbitraryValues: false
        uid:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           placeholder: SELECT-UID
           path: catalog/entities
           valueSelector: metadata.uid
           labelSelector: metadata.name
           allowArbitraryValues: false      
        detail:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           placeholder: Select titles
           path: catalog/entities?filter=metadata.uid={{parameters.uid}}
           valueSelector: metadata.title
           allowArbitraryValues: false
           setContextData:
             component_uid: metadata.uid
             component_name: metadata.name
             component_title: metadata.title




          
