apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: lp-demo
  title: lp-demo
  description: api-demo
spec:
  owner: DCP
  type: service
  parameters:
    - title: Fill in the repo details
      properties:
        test:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: Select-env
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities
            params:
              filter: kind=resource,spec.type=eks,spec.owner=group:default/dcp,metadata.name=aws-31971-dcp-eks-testg-us-west-2-non-prod
            valueSelector: metadata.jenkinsurl
            allowArbitraryValues: false
        uid:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           placeholder: SELECT-UID
           path: catalog/entities
           valueSelector: metadata.uid
           labelSelector: metadata.name
           allowArbitraryValues: false      
        detail:
         type: string
         ui:field: SelectFieldFromApi
         ui:options:
           placeholder: Select titles
           path: catalog/entities?filter=metadata.uid={{parameters.uid}}
           valueSelector: metadata.name
           allowArbitraryValues: false
           #setContextData:
             #component_uid: metadata.uid
             #component_name: metadata.name                
             #component_title: metadata.title              

    steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding_Clone_Clone/pipeline-studio?storeType=INLINE
        inputset:
          aws_account: ${{ parameters.aws_account }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          return: ${{steps.trigger.output.RETURN_VAL}},github_org_name: ${{ parameters.github_org_name}},github_repo_name: ${{ parameters.github_repo_name}}



          
