apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: lp-demo
  title: lp-demo
  description: api-demo
spec:
  owner: DCP
  type: service
  parameters:
    - title: Fill in the repo details
      properties:
        test:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: Select titles
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities
            params:
              filter: kind=resource,spec.type=eks,spec.owner=group:default/dcp,metadata.name=aws-31971-dcp-eks-testg-us-west-2-non-prod
            valueSelector: metadata.jenkinsurl
            allowArbitraryValues: false
        uid:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: Select titles
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities
            params:
              filter: kind=resource,spec.type=eks,spec.owner=group:default/dcp,metadata.name=aws-31971-dcp-eks-testg-us-west-2-non-prod
            valueSelector: metadata.uid
            labelSelector: metadata.name
            allowArbitraryValues: false          
        title:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: Select titles
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities/by-uid/{{parameters.uid}}
            arraySelector: metadata.links
            valueSelector: title
            setContextData:
              exampl_title: title
              exampl_url: url   
              exampl_type: type   
        title_test_2:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            placeholder: title_test_2
            path: proxy/harness-idp-api/ow3wOLKoQASF8ih6yBsvAw/idp/api/catalog/entities/by-uid/{{parameters.uid}}
            #arraySelector: ./metadata            
            valueSelector: metadata.name
        property_title:
          title: title of the link
          readonly: true
          type: string
          ui:field: ContextViewer
          ui:options:
            getContextData: {{formContext.exampl_title}}  
        property_type:
          title: type of the link
          readonly: true
          type: string
          ui:field: ContextViewer
          ui:options:
            getContextData: {{formContext.exampl_type}}                
        formContext:
          title: Live Form Context
          description: DEBUG Context
          type: string
          ui:field: ContextViewer
          ui:options:
            getContextData: {{formContext}}
  
  steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding_Clone_Clone/pipeline-studio?storeType=INLINE
        inputset:
          aws_account: ${{ parameters.aws_account }}
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          return: ${{steps.trigger.output.RETURN_VAL}},github_org_name: ${{ parameters.github_org_name}},github_repo_name: ${{ parameters.github_repo_name}}



          
