apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dev-ecommerce
  description: test
  aws_account: ac100
  aws_env_type: dev
  aws_node_type: t3.large
  aws_region: us-west-1

  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: EKS
  owner: abc
  lifecycle: experimental
