apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dev-ecommerce
  description: test
  aws_account: ac100
  aws_env_type: dev
  aws_node_type: t3.large
  aws_region: us-west-1

  annotations:
    backstage.io/techdocs-ref: dir:.


  links:
    - url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/idp/create/templates/default/eks-self-service-creation
      title: Upgrade
      type: admin-dashboard
    - url: https://admin.example-org.com
      title: Monitor
      type: admin-dashboard
    - url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/idp/create/templates/default/eks-self-service-creation
      title: Delete
      type: admin-dashboard

spec:
  type: EKS
  owner: abc
  lifecycle: experimental
