apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: EKS-self-service-creation
  title: Create EKS Cluster
  description: Create EKS Cluster
spec:
  tag:
    self-service
    eks
  owner: service.owner
  type: resource
parameters:
  - title: Account
    required:
      - aws_account
    properties:
      aws_accounts:
        type: string
        ui:field: SelectFieldFromApi
        ui:options:
          title: AWS Account
          description: AWS Account selected
          placeholder: Choose an AWS Account
          path: proxy/demo-api
          params:
            action: "listAccounts"          
          valueSelector: Id
          allowArbitraryValues: false    
      aws_region:
        type: string
        ui:field: SelectFieldFromApi
        ui:options:
          title: Regions
          description: Regions
          placeholder: Choose a Region
          path: proxy/demo-api
          params:
            action: "listRegions"          
          valueSelector: region
          allowArbitraryValues: false
      vpc:
        type: string
        ui:field: SelectFieldFromApi
        ui:options:
          title: VPC
          description: VPC
          placeholder: Select VPC
          path: proxy/demo-api
          params:
            action: "listVPCs"    
            account_id: "abc"
            region: "us-west-2"
          valueSelector: VpcId
          allowArbitraryValues: false          
  - title: reference
    required:
      - aws_account
    properties:
      aws_account:
        type: string
        value: {{ parameters.aws_account}}
steps:
  - id: trigger
    name: Create-eks-cluster
    action: trigger:harness-custom-pipeline
    input:
      url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/createekspipeline/pipeline-studio/?branch=dev&connectorRef=account.LephanHH&storeType=REMOTE&repoName=demo-catalog
      inputset:
        aws_account: ${{ parameters.aws_account }}
        aws_region: ${{ parameters.aws_region }}
        aws_vpc: ${{ parameters.aws_vpc }}
      apikey: ${{ parameters.token }}
      showOutputVariables: true
output:
  links:
    - title: Pipeline Details
      url: ${{ steps.trigger.output.PipelineUrl }}
