apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: EKS-self-service-creation
  title: Create EKS Cluster
  description: Create EKS Cluster
spec:
  tag:
    self-service
    eks
  owner: service.owner
  type: resource
  parameters:
    - title: "Account"
      required:
        - aws_account
      properties:
        aws_account:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: "AWS Account"
            description: "Pick one of the AWS Account"
            placeholder: "Choose an AWS Account"
            path: proxy/demo-api
            params:
              action: "listAccounts"
            valueSelector: "Id"
            allowArbitraryValues: true
        owner:
          title: Owner
          type: string
          description: Owner of the component
          ui:field: OwnerPicker
          ui:options:
            allowArbitraryValues: true
        token:
          title: "Harness Token"
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken  
    - title: "Region"
      required:
      - aws_region
      properties:
        aws_region:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: "AWS Region"
            description: "Pick Region"
            placeholder: "Choose a region"
            path: proxy/demo-api
            params:
              action: "getAccountRegion"
              account_id: "{{parameters.aws_account}}"
            valueSelector: "region"
            allowArbitraryValues: true
    - title: "VPC / Cluster config"
      required:
      - aws_vpc
      - aws_eks_nane
      - aws_env_type
      - aws_node_type
      properties:
        aws_vpc:
          type: string
          ui:field: SelectFieldFromApi
          ui:options:
            title: VPC
            description: "Pick VPC"
            placeholder: "Choose a VPC"
            path: proxy/demo-api
            params:
              action: "getVPC"
              account_id: "{{parameters.aws_account}}"
              region: "{{parameters.aws_region}}"
            valueSelector: "VpcId"
            allowArbitraryValues: true
        aws_eks_nane:
          type: string
          title: "EKS Name"
          description: "The name of the eks cluster"
          maxLength: 16
          pattern: "^([a-zA-Z][a-zA-Z0-9]*)(-[a-zA-Z0-9]+)*$"
        aws_env_type:
          type: string
          enum:
            - dev
            - prod
          description: "The env type for deployment"
        aws_description:
          type: string
          title: "Cluster Description"
          description: "The description of the cluster"
        aws_node_type:
          type: string
          enum:
            - t3.medium
            - t3.large
            - m5.large
          description: "EC Type size"
  steps:
    - id: trigger
      name: Create-eks-cluster
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding_Clone_Clone/pipeline-studio?storeType=INLINE
        inputset:
          aws_account: ${{ parameters.aws_account }}
          aws_region: ${{ parameters.aws_region }}
          aws_vpc: ${{ parameters.aws_vpc }}
          aws_eks_nane: ${{ parameters.aws_eks_nane }}
          aws_env_type: ${{ parameters.aws_env_type }}
          aws_description: ${{ parameters.aws_description }}
          aws_node_type: ${{ parameters.aws_node_type }}
          owner: ${{ parameter.owner }}

        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}
    text:
      - title: Outputs
        content: |
          return: ${{steps.trigger.output.RETURN_VAL}},github_org_name: ${{ parameters.github_org_name}},github_repo_name: ${{ parameters.github_repo_name}}
          
          
          





          


