apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
# some metadata about the template itself
metadata:
  name: Workflows-Quickstart
  title: Create a New GitHub Repository
  description: Creates a new GitHub Repository 
spec:
  owner: service.owner
  type: service
  # these are the steps which are rendered in the frontend with the form input
  parameters:
    - title: Fill in the repo details
      required:
        - aws_account
        - eks_cluster_name
        - action
      properties:
        aws_account:
          title: aws account
          type: string
          description: AWS Account ID
        eks_cluster_name:
          title: EKS Cluster name
          type: string
          description: EKS CLuster Name
        action:
          title: action
          type: string
          - enum
            update
            delete
        token:
          title: Harness Token
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken       
  steps:
    - id: trigger
      name: Onboarding a New GitHub Repository
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/GitHub_Repository_Onboarding_Clone_Clone/pipeline-studio?storeType=INLINE
        inputset:
        apikey: ${{ parameters.token }}
        showOutputVariables: true


          
