apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Workflow-end-end
  title: Workflow-end-end
  description: Workflow-end-end
spec:
  tag:
    self-service
    eks
  owner: service.owner
  type: resource
  parameters:
    - title: "Page1"
      properties:
        token:
          title: "Harness Token"
          type: string
          ui:widget: password
          ui:field: HarnessAuthToken      
        team:
          title: Team
          type: string
          description: Owner of the component
          ui:field: MyGroupsPicker
        aws_eks_nane:
          title: eks cluster name
          type: string              
          description: cluster name
        environment:
          title: Select Environment
          type: string
          enum:
            - non-prod
            - prod    
      dependencies:
        environment:
          oneOf:
            - properties:
                  environment:
                    enum:
                      - non-prod
                  environment_type:
                    title: Select environment type
                    type: string
                    enum:
                      - dev
                      - test
                      - int
                      - perf
            - properties:
                  environment:
                    enum:
                      - prod
                  environment_type:
                    title: Select environment type
                    type: string
                    enum:
                      - stage
                      - prod         
  steps:
    - id: trigger
      name: Create-eks-cluster
      action: trigger:harness-custom-pipeline
      input:
        url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/ci/orgs/default/projects/DirectTVDemo/pipelines/createeks_Clone2/pipeline-studio?storeType=INLINE
        inputset:
          aws_eks_name: ${{  parameters.aws_eks_nane }}
          env: ${{ parameters.environment_type }}
          user_group: ${{ parameters.team }}
          eksworkflow_url: https://app.harness.io/ng/account/278oQOylSUWVALR6dOgnhg/module/idp/create/templates/default/eks-update-delete-workflow
        apikey: ${{ parameters.token }}
        showOutputVariables: true
  output:
    links:
      - title: Pipeline Details
        url: ${{ steps.trigger.output.PipelineUrl }}


        
